ModMap = ModMap or {}

-- Wheel types (GTA native SetVehicleWheelType)
-- Pastikan tersedia untuk dropdown H1 Wheels
ModMap.wheels = ModMap.wheels or {
  { id = 0,  label = 'Sport' },
  { id = 1,  label = 'Muscle' },
  { id = 2,  label = 'Lowrider' },
  { id = 3,  label = 'SUV' },
  { id = 4,  label = 'Offroad' },
  { id = 5,  label = 'Tuner' },
  { id = 6,  label = 'Bike (Front)' },
  { id = 7,  label = 'High End' },
  { id = 8,  label = "Benny's Original" },
  { id = 9,  label = "Benny's Bespoke" },
  { id = 10, label = 'Open Wheel' },
  { id = 11, label = 'Street' },
  { id = 12, label = 'Track' },
}

-- Body parts mapping (buat tab body H1)
-- modType sesuai GTA mod indices
ModMap.bodyParts = ModMap.bodyParts or {
  { key='spoiler',       label='Spoiler',       modType=0 },
  { key='front_bumper',  label='Front Bumper',  modType=1 },
  { key='rear_bumper',   label='Rear Bumper',   modType=2 },
  { key='side_skirt',    label='Side Skirt',    modType=3 },
  { key='roll_cage',     label='Roll Cage',     modType=5 },
  { key='grille',        label='Grille',        modType=6 },
  { key='hood',          label='Hood',          modType=7 },
  { key='left_fender',   label='Left Fender',   modType=8 },
  { key='right_fender',  label='Right Fender',  modType=9 },
  { key='roof',          label='Roof',          modType=10 },
}

-- Xenon, tint, plate, horn (kalau kamu sudah punya, ini tidak ganggu)
ModMap.xenon = ModMap.xenon or {
  {id = -1, label = 'Default'},
  {id = 0,  label = 'White'},
  {id = 1,  label = 'Blue'},
  {id = 2,  label = 'Electric Blue'},
  {id = 3,  label = 'Mint Green'},
  {id = 4,  label = 'Lime Green'},
  {id = 5,  label = 'Yellow'},
  {id = 6,  label = 'Golden Shower'},
  {id = 7,  label = 'Orange'},
  {id = 8,  label = 'Red'},
  {id = 9,  label = 'Pony Pink'},
  {id = 10, label = 'Hot Pink'},
  {id = 11, label = 'Purple'},
  {id = 12, label = 'Blacklight'},
}

ModMap.windowTints = ModMap.windowTints or {
  {id = 0, label = 'None'},
  {id = 1, label = 'Pure black'},
  {id = 2, label = 'Dark Smoke'},
  {id = 3, label = 'Light Smoke'},
  {id = 4, label = 'Stock'},
  {id = 5, label = 'Green'},
}

ModMap.plateIndexes = ModMap.plateIndexes or {
  {id = 0, label = 'Blue on White 1'},
  {id = 1, label = 'Yellow on Black'},
  {id = 2, label = 'Yellow on Blue'},
  {id = 3, label = 'Blue on White 2'},
  {id = 4, label = 'Blue on White 3'},
  {id = 5, label = 'Yankton'},
  {id = 6, label = 'Ecola'},
  {id = 7, label = 'Las Venturas'},
  {id = 8, label = 'Liberty City'},
  {id = 9, label = 'Los Santos Car Meet'},
  {id = 10, label = 'Los Santos Panic'},
  {id = 11, label = 'Pounders All-Stars'},
  {id = 12, label = 'Sprunk'},
}

ModMap.horns = ModMap.horns or {
  {id = 0,  label = 'Truck Horn'},
  {id = 1,  label = 'Cop Horn'},
  {id = 2,  label = 'Clown Horn'},
  {id = 3,  label = 'Musical Horn 1'},
  {id = 4,  label = 'Musical Horn 2'},
  {id = 5,  label = 'Musical Horn 3'},
  {id = 6,  label = 'Musical Horn 4'},
  {id = 7,  label = 'Musical Horn 5'},
  {id = 8,  label = 'Sad Trombone'},
  {id = 9,  label = 'Classical Horn 1'},
  {id = 10, label = 'Classical Horn 2'},
  {id = 11, label = 'Classical Horn 3'},
  {id = 12, label = 'Classical Horn 4'},
  {id = 13, label = 'Classical Horn 5'},
  {id = 14, label = 'Classical Horn 6'},
  {id = 15, label = 'Classical Horn 7'},
  {id = 16, label = 'Scale - Do'},
  {id = 17, label = 'Scale - Re'},
  {id = 18, label = 'Scale - Mi'},
  {id = 19, label = 'Scale - Fa'},
  {id = 20, label = 'Scale - Sol'},
  {id = 21, label = 'Scale - La'},
  {id = 22, label = 'Scale - Ti'},
  {id = 23, label = 'Scale - Do'},
  {id = 24, label = 'Jazz Horn 1'},
  {id = 25, label = 'Jazz Horn 2'},
  {id = 26, label = 'Jazz Horn 3'},
  {id = 27, label = 'Jazz Horn Loop'},
  {id = 28, label = 'Star Spangled Banner 1'},
  {id = 29, label = 'Star Spangled Banner 2'},
  {id = 30, label = 'Star Spangled Banner 3'},
  {id = 31, label = 'Star Spangled Banner 4'},
  {id = 32, label = 'Classical Horn 8 Loop'},
  {id = 33, label = 'Classical Horn 9 Loop'},
  {id = 34, label = 'Classical Horn 10 Loop'},
  {id = 35, label = 'Classical Horn 8'},
  {id = 36, label = 'Classical Horn 9'},
  {id = 37, label = 'Classical Horn 10'},
  {id = 38, label = 'Funeral Loop'},
  {id = 39, label = 'Funeral'},
  {id = 40, label = 'Spooky Loop'},
  {id = 41, label = 'Spooky'},
  {id = 42, label = 'San Andreas Loop'},
  {id = 43, label = 'San Andreas'},
  {id = 44, label = 'Liberty City Loop'},
  {id = 45, label = 'Liberty City'},
  {id = 46, label = 'Festive 1 Loop'},
  {id = 47, label = 'Festive 1'},
  {id = 48, label = 'Festive 2 Loop'},
  {id = 49, label = 'Festive 2'},
  {id = 50, label = 'Festive 3 Loop'},
  {id = 51, label = 'Festive 3'},
  {id = 52, label = 'Air Horn Low Loop'},
  {id = 53, label = 'Air Horn Low'},
  {id = 54, label = 'Air Horn Medium Loop'},
  {id = 55, label = 'Air Horn Medium'},
  {id = 56, label = 'Air Horn High Loop'},
  {id = 57, label = 'Air Horn High'},
}

return ModMap
