-- shared/paints.lua (FINAL)
-- Dipakai oleh client/nui.lua:
--   - Paints.groups (untuk dropdown H2 "Paint Type")
--   - Paints.list[groupId] (untuk requestPaintOptions)

Paints = Paints or {}

-- urutan dropdown "Paint Type"
Paints.groups = {
  { id = 'Classic',    label = 'Classic' },
  { id = 'Matte',      label = 'Matte' },
  { id = 'Metal',      label = 'Metal' },
  { id = 'Worn',       label = 'Worn' },
  { id = 'Chameleon',  label = 'Chameleon' },
}

-- list per type
Paints.list = {
  Classic = {
    {id = 0,   label = 'Black'},
    {id = 1,   label = 'Graphite'},
    {id = 2,   label = 'Black Steel'},
    {id = 3,   label = 'Dark Steel'},
    {id = 4,   label = 'Silver'},
    {id = 5,   label = 'Bluish Silver'},
    {id = 6,   label = 'Rolled Steel'},
    {id = 7,   label = 'Shadow Silver'},
    {id = 8,   label = 'Stone Silver'},
    {id = 9,   label = 'Midnight Silver'},
    {id = 10,  label = 'Cast Iron Silver'},
    {id = 11,  label = 'Anhracite Black'},
    {id = 27,  label = 'Red'},
    {id = 28,  label = 'Torino Red'},
    {id = 29,  label = 'Formula Red'},
    {id = 30,  label = 'Blaze Red'},
    {id = 31,  label = 'Grace Red'},
    {id = 32,  label = 'Garnet Red'},
    {id = 33,  label = 'Sunset Red'},
    {id = 34,  label = 'Cabernet Red'},
    {id = 35,  label = 'Candy Red'},
    {id = 36,  label = 'Sunrise Orange'},
    {id = 38,  label = 'Orange'},
    {id = 49,  label = 'Dark Green'},
    {id = 50,  label = 'Racing Green'},
    {id = 51,  label = 'Sea Green'},
    {id = 52,  label = 'Olive Green'},
    {id = 53,  label = 'Bright Green'},
    {id = 54,  label = 'Gasoline Green'},
    {id = 61,  label = 'Galaxy Blue'},
    {id = 62,  label = 'Dark Blue'},
    {id = 63,  label = 'Saxon Blue'},
    {id = 64,  label = 'Blue'},
    {id = 65,  label = 'Mariner Blue'},
    {id = 66,  label = 'Harbor Blue'},
    {id = 67,  label = 'Diamond Blue'},
    {id = 68,  label = 'Surf Blue'},
    {id = 69,  label = 'Nautical Blue'},
    {id = 70,  label = 'Ultra Blue'},
    {id = 71,  label = 'Schafter Purple'},
    {id = 72,  label = 'Spinnaker Purple'},
    {id = 73,  label = 'Racing Blue'},
    {id = 74,  label = 'Light Blue'},
    {id = 88,  label = 'Yellow'},
    {id = 89,  label = 'Race Yellow'},
    {id = 90,  label = 'Bronze'},
    {id = 91,  label = 'Dew Yellow'},
    {id = 92,  label = 'Lime Green'},
    {id = 94,  label = 'Feltzer Brown'},
    {id = 95,  label = 'Creeen Brown'},
    {id = 96,  label = 'Chocolate Brown'},
    {id = 97,  label = 'Maple Brown'},
    {id = 98,  label = 'Saddle Brown'},
    {id = 99,  label = 'Bleached Brown'},
    {id = 100, label = 'Moss Brown'},
    {id = 101, label = 'Bison Brown'},
    {id = 102, label = 'Woodbeech Brown'},
    {id = 103, label = 'Beechwood Brown'},
    {id = 104, label = 'Sienna Brown'},
    {id = 105, label = 'Sandy Brown'},
    {id = 106, label = 'Bleached Brown'},
    {id = 107, label = 'Cream'},
    {id = 111, label = 'Ice White'},
    {id = 112, label = 'Frost White'},
    {id = 135, label = 'Hot Pink'},
    {id = 136, label = 'Salmon Pink'},
    {id = 137, label = 'Pfsiter Pink'},
    {id = 138, label = 'Bright Orange'},
    {id = 141, label = 'Midnight Blue'},
    {id = 142, label = 'Midnight Purple'},
    {id = 143, label = 'Wine Red'},
    {id = 145, label = 'Bright Purple'},
    {id = 147, label = 'Carbon Black'},
    {id = 150, label = 'Lava Red'},
  },

  Matte = {
    {id = 12,  label = 'Black'},
    {id = 13,  label = 'Gray'},
    {id = 14,  label = 'Light Gray'},
    {id = 39,  label = 'Red'},
    {id = 40,  label = 'Dark Red'},
    {id = 41,  label = 'Orange'},
    {id = 42,  label = 'Yellow'},
    {id = 55,  label = 'Lime Green'},
    {id = 82,  label = 'Dark Blue'},
    {id = 83,  label = 'Blue'},
    {id = 84,  label = 'Midnight Blue'},
    {id = 131, label = 'Ice White'},
    {id = 148, label = 'Schafter Purple'},
    {id = 149, label = 'Midnight Purple'},
    {id = 151, label = 'Forest Green'},
    {id = 152, label = 'Olive Darb'},
    {id = 153, label = 'Dark Earth'},
    {id = 154, label = 'Desert Tan'},
    {id = 155, label = 'Foliage Green'},
  },

  Metal = {
    {id = 117, label = 'Brushed Steel'},
    {id = 118, label = 'Brushed Black Steel'},
    {id = 119, label = 'Brushed Aluminum'},
    {id = 120, label = 'Chrome'},
    {id = 158, label = 'Pure Gold'},
    {id = 159, label = 'Brushed Gold'},
  },

  Worn = {
    {id = 21,  label = 'Black'},
    {id = 22,  label = 'Graphite'},
    {id = 23,  label = 'Silver Grey'},
    {id = 24,  label = 'Silver'},
    {id = 25,  label = 'Blue Silver'},
    {id = 26,  label = 'Shadow Silver'},
    {id = 46,  label = 'Red'},
    {id = 47,  label = 'Golden Red'},
    {id = 48,  label = 'Dark Red'},
    {id = 58,  label = 'Dark Green'},
    {id = 59,  label = 'Green'},
    {id = 60,  label = 'Sea Wash'},
    {id = 85,  label = 'Dark blue'},
    {id = 86,  label = 'Blue'},
    {id = 87,  label = 'Light blue'},
    {id = 113, label = 'Honey Beige'},
    {id = 114, label = 'Brown'},
    {id = 115, label = 'Dark Brown'},
    {id = 116, label = 'straw beige'},
    {id = 121, label = 'Off White'},
    {id = 123, label = 'Orange'},
    {id = 124, label = 'Light Orange'},
    {id = 126, label = 'Taxi Yellow'},
    {id = 130, label = 'Orange'},
    {id = 132, label = 'White'},
    {id = 133, label = 'Olive Army Green'},
  },

  Chameleon = {
    {id = 161, label = 'Anodized Red Pearl'},
    {id = 162, label = 'Anodized Wine Pearl'},
    {id = 163, label = 'Anodized Purple Pearl'},
    {id = 164, label = 'Anodized Blue Pearl'},
    {id = 165, label = 'Anodized Green Pearl'},
    {id = 166, label = 'Anodized Lime Pearl'},
    {id = 167, label = 'Anodized Copper Pearl'},
    {id = 168, label = 'Anodized Bronze Pearl'},
    {id = 169, label = 'Anodized Champagne Pearl'},
    {id = 170, label = 'Anodized Gold Pearl'},
    {id = 171, label = 'Green/Blue Flip'},
    {id = 172, label = 'Green/Red Flip'},
    {id = 173, label = 'Green/Brown Flip'},
    {id = 174, label = 'Green/Turquoise Flip'},
    {id = 175, label = 'Green/Purple Flip'},
    {id = 176, label = 'Teal/Purple Flip'},
    {id = 177, label = 'Turquoise/Red Flip'},
    {id = 178, label = 'Turquoise/Purple Flip'},
    {id = 179, label = 'Cyan/Purple Flip'},
    {id = 180, label = 'Blue/Pink Flip'},
    {id = 181, label = 'Blue/Green Flip'},
    {id = 182, label = 'Purple/Red Flip'},
    {id = 183, label = 'Purple/Green Flip'},
    {id = 184, label = 'Magenta/Green Flip'},
    {id = 185, label = 'Magenta/Yellow Flip'},
    {id = 186, label = 'Burgundy/Green Flip'},
    {id = 187, label = 'Magenta/Cyan Flip'},
    {id = 188, label = 'Copper/Purple Flip'},
    {id = 189, label = 'Magenta/Orange Flip'},
    {id = 190, label = 'Red/Orange Flip'},
    {id = 191, label = 'Orange/Purple Flip'},
    {id = 192, label = 'Orange/Blue Flip'},
    {id = 193, label = 'White/Purple Flip'},
    {id = 194, label = 'Red/Rainbow Flip'},
    {id = 195, label = 'Blue/Rainbow Flip'},
    {id = 196, label = 'Dark Green Pearl'},
    {id = 197, label = 'Dark Teal Pearl'},
    {id = 198, label = 'Dark Blue Pearl'},
    {id = 199, label = 'Dark Purple Pearl'},
    {id = 200, label = 'Oil Slick Pearl'},
    {id = 201, label = 'Light Green Pearl'},
    {id = 202, label = 'Light Blue Pearl'},
    {id = 203, label = 'Light Purple Pearl'},
    {id = 204, label = 'Light Pink Pearl'},
    {id = 205, label = 'Off White Pearl'},
    {id = 206, label = 'Cute Pink Pearl'},
    {id = 207, label = 'Baby Yellow Pearl'},
    {id = 208, label = 'Baby Green Pearl'},
    {id = 209, label = 'Baby Blue Pearl'},
    {id = 210, label = 'Cream Pearl'},
    {id = 211, label = 'White Prismatic Pearl'},
    {id = 212, label = 'Graphite Prismatic Pearl'},
    {id = 213, label = 'Blue Prismatic Pearl'},
    {id = 214, label = 'Purple Prismatic Pearl'},
    {id = 215, label = 'Hot Pink Prismatic Pearl'},
    {id = 216, label = 'Red Prismatic Pearl'},
    {id = 217, label = 'Green Prismatic Pearl'},
    {id = 218, label = 'Black Prismatic Pearl'},
    {id = 219, label = 'Oil Spill Prismatic Pearl'},
    {id = 220, label = 'Rainbow Prismatic Pearl'},
    {id = 221, label = 'Black Holographic Pearl'},
    {id = 222, label = 'White Holographic Pearl'},
    {id = 223, label = 'Fubuki-jo Specials: Monochrome'},
    {id = 224, label = 'Fubuki-jo Specials: Night & Day'},
    {id = 225, label = 'Fubuki-jo Specials: The Verlierer'},
    {id = 226, label = 'Fubuki-jo Specials: Sprunk Extreme'},
    {id = 227, label = 'Fubuki-jo Specials: Vice City'},
    {id = 228, label = 'Fubuki-jo Specials: Synthwave Night'},
    {id = 229, label = 'Fubuki-jo Specials: Four Seasons'},
    {id = 230, label = 'Fubuki-jo Specials: M9 Throwback'},
    {id = 231, label = 'Fubuki-jo Specials: Bubblegum'},
    {id = 232, label = 'Fubuki-jo Specials: Full Rainbow'},
    {id = 233, label = 'Fubuki-jo Specials: Sunset'},
    {id = 234, label = 'Fubuki-jo Specials: The Seven'},
    {id = 235, label = 'Fubuki-jo Specials: Kamen Rider'},
    {id = 236, label = 'Fubuki-jo Specials: Chromatic'},
    {id = 237, label = "Fubuki-jo Specials: It's Christmas!"},
    {id = 238, label = 'Fubuki-jo Specials: Temperature'},
    {id = 239, label = 'Fubuki-jo Specials: HSW Badge'},
    {id = 240, label = 'Fubuki-jo Specials: Anod. Lightning'},
    {id = 241, label = 'Fubuki-jo Specials: Emeralds'},
    {id = 242, label = 'Fubuki-jo Specials: Fubuki Castle'},
  },
}

return Paints
